# Este archivo configura el analizador, que analiza estáticamente el código Dart para
# verificar errores, advertencias y lints.
#
# Los problemas identificados por el analizador se muestran en la interfaz de usuario
# de los IDEs que soportan Dart (https://dart.dev/tools#ides-and-editors). También puede
# ejecutarse desde la línea de comandos mediante `flutter analyze`.

# La siguiente línea activa un conjunto de lints recomendados para apps Flutter,
# paquetes y plugins, diseñados para fomentar buenas prácticas de programación.
include: package:flutter_lints/flutter.yaml

linter:
  # Las reglas de lint aplicadas a este proyecto pueden ser personalizadas en la
  # siguiente sección para desactivar reglas del archivo `package:flutter_lints/flutter.yaml`
  # o para habilitar reglas adicionales. Una lista de todas las lints disponibles
  # y su documentación está publicada en https://dart.dev/lints.
  
  rules:
    # Regla desactivada: se desactiva la recomendación de usar constructores `const` cuando no es necesario.
    prefer_const_constructors: false

    # Regla desactivada: se desactiva la recomendación de usar `final` en los campos cuando no se cambian.
    prefer_final_fields: false

    # Regla desactivada: se desactiva la recomendación de usar `Key` en los constructores de widgets.
    use_key_in_widget_constructors: false

    # Regla desactivada: se desactiva la recomendación de preferir literales constantes para crear colecciones inmutables.
    prefer_const_literals_to_create_immutables: false

    # Regla desactivada: se desactiva la recomendación de usar `const` en los parámetros inmutables.
    prefer_const_constructors_in_immutables: false

    # Regla desactivada: se desactiva la recomendación de evitar el uso de `print()` en el código.
    avoid_print: false

    # Descomentado para habilitar la recomendación de usar comillas simples en lugar de dobles.
    prefer_single_quotes: true

# Información adicional sobre este archivo se puede encontrar en:
# https://dart.dev/guides/language/analysis-options
