name: CoachCraft
description: "Una app para los amantes del futsal."
# El siguiente valor evita que el paquete se publique accidentalmente
# en pub.dev usando `flutter pub publish`. Esto es preferido para paquetes privados.
publish_to: 'none' # Elimina esta línea si deseas publicar en pub.dev

# Define la versión y el número de compilación para tu aplicación.
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencias principales que necesita tu aplicación para funcionar.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0 # Especifica una versión compatible con Firebase v9 o superior
  firebase_auth: ^5.1.2
  firebase_core_web: ^2.3.0
  cloud_firestore_web: ^4.0.0
  google_sign_in: ^6.2.1
  pdf: ^3.11.1
  printing: ^5.13.1
  firebase_storage: ^12.2.0
  image_picker: ^1.1.2
  flutter_gif: ^0.0.4
  flutter_image: ^4.1.11
  intl: ^0.19.0
  flutter_colorpicker: ^1.0.0
  flutter_screen_recording: ^2.0.16
  path_provider: ^2.0.9
  file_picker: ^8.1.2
  url_launcher: ^6.3.0
  email_validator: ^3.0.0
  provider: ^6.1.2
  fl_chart: ^0.69.0
  permission_handler: ^11.3.1
  video_player: ^2.9.2
  google_fonts: ^6.2.1
  firebase_auth_mocks: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.0
  test: ^1.25.7


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf

  # Si deseas agregar fuentes personalizadas, puedes hacerlo aquí.
  # Asegúrate de que las rutas de los archivos de las fuentes sean correctas.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
