// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkwhh0S6ej6QN-6ILtMc_aubEekQq5txM',
    appId: '1:201135652207:web:ae22a721acd15a6b91fc9a',
    messagingSenderId: '201135652207',
    projectId: 'coachcraft',
    authDomain: 'coachcraft.firebaseapp.com',
    storageBucket: 'coachcraft.appspot.com',
    measurementId: 'G-68P7ZFXB39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLix7bf2J3zNr8i1dvNG_dQVk0vqXktYs',
    appId: '1:201135652207:android:5da8f43095d4884691fc9a',
    messagingSenderId: '201135652207',
    projectId: 'coachcraft',
    storageBucket: 'coachcraft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCo-lsMtE56unCP61FBEp0b8TPIwHbGoI',
    appId: '1:201135652207:ios:0ad8ad990738209891fc9a',
    messagingSenderId: '201135652207',
    projectId: 'coachcraft',
    storageBucket: 'coachcraft.appspot.com',
    iosBundleId: 'com.example.pizzaratech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCo-lsMtE56unCP61FBEp0b8TPIwHbGoI',
    appId: '1:201135652207:ios:0ad8ad990738209891fc9a',
    messagingSenderId: '201135652207',
    projectId: 'coachcraft',
    storageBucket: 'coachcraft.appspot.com',
    iosBundleId: 'com.example.pizzaratech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkwhh0S6ej6QN-6ILtMc_aubEekQq5txM',
    appId: '1:201135652207:web:c2f0afad4c2483c291fc9a',
    messagingSenderId: '201135652207',
    projectId: 'coachcraft',
    authDomain: 'coachcraft.firebaseapp.com',
    storageBucket: 'coachcraft.appspot.com',
    measurementId: 'G-C9TLYTPBYW',
  );

}